# Pipeline speed and durability property
pipeline_strategy:
# General options for the job
build:
  allow_concurrent: false
  properties:
    # Days to keep old builds
    days_to_keep: -1
    # Number of old builds to keep
    num_to_keep: 5
  # A list of parameters when the pipeline is parameterized
  parameters:
    # Name of parameter. Usually named using CAPITAL LETTERS
    - name: GREET_NAME
      # String value for the parameter. Can be left empty
      value: Hey There
      # A helper text for the parameter. Can be empty
      description: Name of the person to greet
# How the job should be trigered. Below are the default values
triggers:
  on_push: false
  on_merge_request: false
  on_merge_accept: false
  on_merge_close: false
  on_merge_approve: false
  # When to rerun the job for an existing merge request. source/both/never
  on_open_merge_on_push: source
# Information of where to find the jenkins file
pipeline:
  # The .git git url.
  git_url: https://github.com/souravatta/Install-Configure.git
  # The credentials to use
  creds_id: github
  # Branch or tag to use
  branch: master
  # Location of Jenkinsfile
  script_path: Jenkinsfile
